// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


addEventListener("fetch", (function ($$event) {
        var jsonData = JSON.stringify({
              hello: "WORLD"
            });
        var respHeaders = {
          headers: {
            "Content-Type": "application/json;charset=UTF-8"
          }
        };
        return $$event.respondWith(new Response(jsonData, respHeaders));
      }));

/*  Not a pure module */
